# Generated by Django 3.2.5 on 2022-03-03 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('S', 'Select'), ('M', 'Male'), ('F', 'Female')], default='S', max_length=3)),
                ('age', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('activity', models.CharField(choices=[('S', 'Select'), ('IA', 'Barely - Somedays a year'), ('SL', 'Slightly - Somedays every month'), ('MD', 'Moderate - Every couple of weeks'), ('AT', 'Active - daily or every other day')], default='S', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
