# Generated by Django 3.2.5 on 2022-03-19 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220318_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logworkout',
            name='time_hr',
        ),
        migrations.RemoveField(
            model_name='logworkout',
            name='time_min',
        ),
        migrations.RemoveField(
            model_name='logworkout',
            name='user',
        ),
        migrations.AddField(
            model_name='logworkout',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
