# Generated by Django 3.2.5 on 2022-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_logworkout_currdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logworkout',
            name='currdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
